image: docker:latest
services:
  - docker:dind

.checkmarx_sast:
  stage: test
  image:
    name: docker.io/checkmarx/cx-flow
    entrypoint: ['']
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml 
        --scan 
        --cx-team="${CHECKMARX_TEAM}"
        --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" 
        --app="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" 
        --cx-flow.break-build=false
        --f=. 
    - mv *.zip cx.zip
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - cx.zip
