include:
#  - remote: 'https://gitlab.com/CxDemoGroup/CxDemoApp/-/raw/master/kics.yml'
#  - remote: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/master/templates/gitlab/v2/Checkmarx.gitlab-ci.yml'

  #james test new v3
  - Checkmarx.gitlab-ci.yml

variables:
  SECURITY_DASHBOARD_ON_MR: "true"
 #   CHECKMARX_PRESET: "High and Medium"
 #   CHECKMARX_EXCLUDE_FOLDERS: ".git/"
 #   KICS_BLOCK_ON_HIGH: "false"
