#include: '.checkmarx.yml'
#include: #'.checkmarx-template.yml'
include: 
  - remote: 'https://gitlab.com/CxDemoGroup/CxDemoApp/-/raw/master/Checkmarx.gitlab-ci.yml'

#checkmarx-scan:
#  variables:
#    CHECKMARX_PRESET: "OWASP TOP 10 - 2017"
    #CX_ENABLED_VULNERABILITY_SCANNERS: sast, sca

#stages:
#  - test

an_action:
  stage: test
  only:
    - master
  script:
    - echo "This is a scan"
