include: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml'

variables:
    #
    #CHECKMARX_BUG_TRACKER: "GitLabDashboard"
    CHECKMARX_EXCLUDE_FOLDERS: "src/"
    CHECKMARX_SCAN_PRESET: "OWASP TOP 10 - 2017"
    CHECKMARX_DOCKER_IMAGE: "cx-flow:ed5a7fd"
    PARAMS: "--checkmarx.preset='OWASP TOP 10 - 2017'"
    CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: "sast,sca"
    SCA_TEAM: "/CxServer/SCA-PM/Champions/jbrots"
    SCA_FILTER_SEVERITY: "High"

