include: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml'

variables:
    CHECKMARX_DOCKER_IMAGE: "cx-flow:ed5a7fd"
    CHECKMARX_SETTINGS_OVERRIDE: "true"
    #CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: "sast,sca"
    #SCA_TEAM: "/CxServer/SCA-PM/Champions/jbrots"
    #SCA_FILTER_SEVERITY: "High"

