include: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/master/templates/gitlab/v2/Checkmarx.gitlab-ci.yml'

variables:
    CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: "sast, sca"
    SCA_FILTER_SEVERITY: "high"
    PARAMS: "--codebashing.codebashingApiUrl=https://api.codebashing.com/lessons --codebashing.tenantBaseUrl=https://learn.codebashing.com/ --codebashing.apiSecret=cMu2Aokrafsc6+WVnuwWox1QTsjvAknDz1huEg8Lhp0="

