variables:
    CX_FLOW_BUG_TRACKER: $BUG_TRACKER
    CX_FLOW_BUG_TRACKER_IMPL: $BUG_TRACKER
    CHECKMARX_INCREMENTAL: "false"
    CHECKMARX_PRESET: "High and Medium"
    CX_PROJECT: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    APP: $CI_PROJECT_NAME
    NAMESPACE: $CI_PROJECT_NAMESPACE
    REPO_NAME: $CI_PROJECT_NAME
    REPO_URL: $CI_REPOSITORY_URL
    CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: sast
    CX_TEAM: $CHECKMARX_TEAM
    BRANCH: $CI_COMMIT_BRANCH
    CX_FLOW_BREAK_BUILD: "false"
    GITLAB_BLOCK_MERGE: "false"
    GITLAB_ERROR_MERGE: "false"
    PARAMS: ""

cx-scan:
  stage: test
  only:
    - master
  variables:
  image:
    name: checkmarx/cx-flow
    entrypoint: ['']
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml
          --scan 
          --app="${APP}" 
          --namespace="${NAMESPACE}" 
          --repo-name="${REPO_NAME}" 
          --repo-url="${REPO_URL}" 
          --preset="${CHECKMARX_PRESET}"
          --cx-team="${CX_TEAM}" 
          --cx-project="${CX_PROJECT}" 
          --branch="${BRANCH}"
          --spring.profiles.active="${CX_FLOW_ENABLED_VULNERABILITY_SCANNERS}" 
          --f=. 
          ${PARAMS}

  artifacts:
    when: on_success
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json


cx-scan-mr:
  stage: test
  only:
    - merge_requests
  variables:
      GITLAB_TOKEN: $GITLAB_TOKEN
  image:   
    name: checkmarx/cx-flow
    entrypoint: ['']
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml
          --scan 
          --app="${APP}" 
          --namespace="${NAMESPACE}" 
          --repo-name="${REPO_NAME}" 
          --repo-url="${REPO_URL}" 
          --cx-team="${CX_TEAM}" 
          --cx-project="${CX_PROJECT}" 
          --branch="${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
          --bug-tracker=GITLABMERGE
          --preset="${CHECKMARX_PRESET}"
          --project-id="${CI_PROJECT_ID}" 
          --merge-id="${CI_MERGE_REQUEST_IID}" 
          --spring.profiles.active="${CX_FLOW_ENABLED_VULNERABILITY_SCANNERS}" 
          --f=. 
          ${PARAMS} 
