# these variables can be overwritten within your .gitlab-ci.yml file
variables:
    CX_FLOW_BUG_TRACKER: "GitLab"             # Should be GitLab or GitLabDashboard.  It will be set to GitLabMerge automatially during a MR
    CX_FLOW_BUG_TRACKER_IMPL: "GitLab"
    CHECKMARX_EXCLUDE_FILES: ""               # exclude specific file types from the Checkmarx scan
    CHECKMARX_EXCLUDE_FOLDERS: ".git/"        # exclude specific directories from the Checkmarx scan
    CHECKMARX_SEVERITY: "High"                # create issues filtering on Severity (i.e. "High")
    CHECKMARX_CATEGORY: ""                    # create issues filtering on Category (i.e. ) 
    CHECKMARX_CWE: ""                         # create issues filtering on Cwe (i.e. 89, 94)
    CHECKMARX_STATUS: ""                      # create issues filtering on Status (i.e. "Confirmed")
    CHECKMARX_INCREMENTAL: "false"            # Scan in incremental mode (True/False)
    CHECKMARX_PRESET: "High and Medium"       # Preset to use during scan
    CHECKMARX_PROJECT: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"  # Checkmarx Project name (i.e. FrontEnd-Dev)
    CHECKMARX_APP: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    CHECKMARX_NAMESPACE: $CI_PROJECT_NAMESPACE
    CHECKMARX_REPO_NAME: $CI_PROJECT_NAME
    CHECKMARX_REPO_URL: $CI_REPOSITORY_URL
    CHECKMARX_ENABLED_VULNERABILITY_SCANNERS: "sast" # scanners (i.e. "sast, sca")
    CHECKMARX_TEAM: "$CHECKMARX_TEAM"                # Checkmarx team name
    CHECKMARX_BRANCH: "$CI_COMMIT_REF_NAME" # ?? "$CI_COMMIT_BRANCH"
    CX_FLOW_BREAK_BUILD: "false"
    GITLAB_BLOCK_MERGE: "false"
    GITLAB_ERROR_MERGE: "false"
    CHECKMARX_PARAMS: ""                      # list of additional parameters (i.e. )

checkmarx-scan-merge-request:
  stage: test
  only:
    refs:
      - merge_requests
  image:   
    name: checkmarx/cx-flow:8e27de2
    entrypoint: ['']
  before_script:
    - |
      export CX_FLOW_BUG_TRACKER="GITLABMERGE"
      export CHECKMARX_MERGE_ID="--merge-id=${CI_MERGE_REQUEST_IID}"
  script:
    - echo "Hello World"
    - echo ${CHECKMARX_NAMESPACE}
    - echo ${CHECKMARX_REPO_NAME}
    - echo ${CHECKMARX_REPO_URL}
    - echo ${CHECKMARX_PROJECT}
    - echo ${CI_COMMIT_REF_NAME}
    - cat ${CX_FLOW_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml
      --scan 
      --app="${CHECKMARX_APP}" 
      --namespace="${CHECKMARX_NAMESPACE}" 
      --repo-name="${CHECKMARX_REPO_NAME}" 
      --repo-url="${CHECKMARX_REPO_URL}" 
      --cx-team="${CHECKMARX_TEAM}" 
      --cx-project="${CHECKMARX_PROJECT}" 
      --branch="${CI_COMMIT_REF_NAME}"
      --bug-tracker="${CX_FLOW_BUG_TRACKER}"
      --preset="${CHECKMARX_PRESET}"
      --severity="${CHECKMARX_SEVERITY}"
      --cwe="${CHECKMARX_CWE}"
      --category="${CHECKMARX_CATEGORY}"
      --status="${CHECKMARX_STATUS}"
      --exclude-files="${CHECKMARX_EXCLUDE_FILES}"
      --exclude-folders="${CHECKMARX_EXCLUDE_FOLDERS}"
      --project-id="${CI_PROJECT_ID}" 
      --spring.profiles.active="${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}" 
      --f=. 
      ${CHECKMARX_MERGE_ID}
      ${CHECKMARX_PARAMS}

checkmarx-scan-push:
  stage: test
  only:
    variables:
      - $CX_FLOW_BUG_TRACKER != "GitLabDashboard"
    refs:
      - master
  image:   
    name: checkmarx/cx-flow:8e27de2
    entrypoint: ['']
  script:
    - echo "Hello World"
    - echo ${CHECKMARX_NAMESPACE}
    - echo ${CHECKMARX_REPO_NAME}
    - echo ${CHECKMARX_REPO_URL}
    - echo ${CHECKMARX_PROJECT}
    - echo ${CI_COMMIT_REF_NAME}
    - cat ${CX_FLOW_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml
      --scan 
      --app="${CHECKMARX_APP}" 
      --namespace="${CHECKMARX_NAMESPACE}" 
      --repo-name="${CHECKMARX_REPO_NAME}" 
      --repo-url="${CHECKMARX_REPO_URL}" 
      --cx-team="${CHECKMARX_TEAM}" 
      --cx-project="${CHECKMARX_PROJECT}" 
      --branch="${CI_COMMIT_REF_NAME}"
      --bug-tracker="${CX_FLOW_BUG_TRACKER}"
      --preset="${CHECKMARX_PRESET}"
      --severity="${CHECKMARX_SEVERITY}"
      --cwe="${CHECKMARX_CWE}"
      --category="${CHECKMARX_CATEGORY}"
      --status="${CHECKMARX_STATUS}"
      --exclude-files="${CHECKMARX_EXCLUDE_FILES}"
      --exclude-folders="${CHECKMARX_EXCLUDE_FOLDERS}"
      --project-id="${CI_PROJECT_ID}" 
      --spring.profiles.active="${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}" 
      --f=. 
      ${CHECKMARX_PARAMS}

checkmarx-scan-dashboard:

  stage: test
  only:
    variables:
      - $CX_FLOW_BUG_TRACKER == "GitLabDashboard"
    refs:
      - master
  image:   
    name: checkmarx/cx-flow:8e27de2
    entrypoint: ['']
  script:
    - echo "Hello World"
    - echo ${CHECKMARX_NAMESPACE}
    - echo ${CHECKMARX_REPO_NAME}
    - echo ${CHECKMARX_REPO_URL}
    - echo ${CHECKMARX_PROJECT}
    - echo ${CI_COMMIT_REF_NAME}
    - cat ${CX_FLOW_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml
      --scan 
      --app="${CHECKMARX_APP}" 
      --namespace="${CHECKMARX_NAMESPACE}" 
      --repo-name="${CHECKMARX_REPO_NAME}" 
      --repo-url="${CHECKMARX_REPO_URL}" 
      --cx-team="${CHECKMARX_TEAM}" 
      --cx-project="${CHECKMARX_PROJECT}" 
      --branch="${CI_COMMIT_REF_NAME}"
      --bug-tracker="${CX_FLOW_BUG_TRACKER}"
      --preset="${CHECKMARX_PRESET}"
      --severity="${CHECKMARX_SEVERITY}"
      --cwe="${CHECKMARX_CWE}"
      --category="${CHECKMARX_CATEGORY}"
      --status="${CHECKMARX_STATUS}"
      --exclude-files="${CHECKMARX_EXCLUDE_FILES}"
      --exclude-folders="${CHECKMARX_EXCLUDE_FOLDERS}"
      --project-id="${CI_PROJECT_ID}" 
      --spring.profiles.active="${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}" 
      --f=. 
      ${CHECKMARX_PARAMS}
  artifacts:
    reports:
      sast: gl-sast-report.json
      dependency_scanning: gl-dependency-scanning-report.json
