##
logging:
  file:
    name: cx-flow.log

cx-flow:
  bug-tracker:  ${CHECKMARX_BUG_TRACKER}
  bug-tracker-impl:
    - ${CHECKMARX_BUG_TRACKER}
    - GitLab
    - GitLabDashboard
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  codebash-url: https://checkmarx-demo.codebashing.com/courses/
  break-build: true
  enabled-vulnerability-scanners: ${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}

checkmarx:
  version: 9.0
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: ${CHECKMARX_SERVER}
  url: ${CHECKMARX_SERVER}/cxrestapi
  portal-url: ${CHECKMARX_SERVER}/cxwebinterface/Portal/CxWebService.asmx
  multi-tenant: true
  incremental: false
  scan-timeout: 120

sca:
  appUrl:  https://sca.scacheckmarx.com
  apiUrl:  https://api.scacheckmarx.com
  accessControlUrl:  https://platform.checkmarx.net
  tenant: ${CHECKMARX_SCA_TENANT}
  username: ${CHECKMARX_SCA_USERNAME}
  password: ${CHECKMARX_SCA_PASSWORD}

gitlab:
  api-url: https://gitlab.com/api/v4/
  false-positive-label: false-positive
  url: https://gitlab.com
  error-merge: true
  cx-summary: true 
  file-path: ./gl-sast-report.json
