#
# This file is a template to be used to automate Checkmarx Scans in GitLab's CI/CD.  Just include it your .gitlab-ci.yml file:
#

# these variables can be overwritten within your .gitlab-ci.yml file
variables:
    CHECKMARX_DOCKER_IMAGE: "cxflow"
    CHECKMARX_CLIENT_SECRET: "014DF517-39D1-4453-B7B3-9930C563627C"
    CHECKMARX_BUG_TRACKER: "GitLab"             # If GitLab, will create GitLab Issues.
                                              # It will be set to GitLabMerge automatially during a MR
    CHECKMARX_BUG_TRACKER_IMPL: "$CHECKMARX_BUG_TRACKER"
    CHECKMARX_EXCLUDE_FILES: ""               # exclude specific file types from the Checkmarx scan
    CHECKMARX_EXCLUDE_FOLDERS: ".git/"        # exclude specific directories from the Checkmarx scan
    CHECKMARX_FILTER_SEVERITY: "High"         # create issues filtering on Severity (i.e. "High")
    CHECKMARX_FILTER_CATEGORY: ""             # create issues filtering on Category (i.e. ) 
    CHECKMARX_FILTER_CWE: ""                  # create issues filtering on Cwe (i.e. 89, 94)
    CHECKMARX_FILTER_STATUS: ""               # create issues filtering on Status (i.e. "Confirmed")
    CHECKMARX_INCREMENTAL: "false"            # Scan in incremental mode (True/False)
    CHECKMARX_SCAN_PRESET: "Android"  # Preset to use during scan
    CHECKMARX_PROJECT: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"  # Checkmarx Project name (i.e. FrontEnd-Dev)
    CHECKMARX_APP: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    CHECKMARX_NAMESPACE: $CI_PROJECT_NAMESPACE
    CHECKMARX_REPO_NAME: $CI_PROJECT_NAME
    CHECKMARX_REPO_URL: $CI_REPOSITORY_URL
    CHECKMARX_ENABLED_VULNERABILITY_SCANNERS: "sast" # scanners (i.e. "sast, sca")
    CHECKMARX_TEAM: "$CHECKMARX_TEAM"         # Checkmarx team name
    CHECKMARX_BRANCH: "$CI_COMMIT_REF_NAME"   # ?? "$CI_COMMIT_BRANCH"
    CHECKMARX_BREAK_BUILD: "false"
    GITLAB_BLOCK_MERGE: "false"
    GITLAB_ERROR_MERGE: "false"
    CXFLOW_PARAMS: ""                      # list of additional parameters (i.e. )

checkmarx-scan-merge-request:
  stage: test
  only:
    refs:
      - merge_requests
  image:   
    name: checkmarx/"${CHECKMARX_DOCKER_IMAGE}"
    entrypoint: ['']
  script:
    - java -jar /app/cx-flow.jar
      --scan 
      --app="${CI_PROJECT_NAME-$CI_COMMIT_REF_NAME}" 
      --namespace="${CHECKMARX_NAMESPACE}" 
      --repo-name="${CHECKMARX_REPO_NAME}" 
      --repo-url="${CHECKMARX_REPO_URL}" 
      --cx-team="${CHECKMARX_TEAM}" 
      --cx-project="${CHECKMARX_PROJECT}" 
      --branch="${CI_COMMIT_REF_NAME}"
      --bug-tracker="GITLABMERGE"
      --checkmarx.scan-preset="${CHECKMARX_SCAN_PRESET}"
      --cx-flow.filter-severity="${CHECKMARX_FILTER_SEVERITY}"
      --cx-flow.filter-cwe="${CHECKMARX_FILTER_CWE}"
      --cx-flow.filter-category="${CHECKMARX_FILTER_CATEGORY}"
      --cx-flow.filter-status="${CHECKMARX_FILTER_STATUS}"
      --checkmarx.exclude-files="${CHECKMARX_EXCLUDE_FILES}"
      --checkmarx.exclude-folders="${CHECKMARX_EXCLUDE_FOLDERS}"
      --project-id="${CI_PROJECT_ID}" 
      --spring.profiles.active="${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}" 
      --f=. 
      --merge-id=${CI_MERGE_REQUEST_IID}
      ${CXFLOW_PARAMS}

checkmarx-scan-push:
  stage: test
  only:
    variables:
      - $CHECKMARX_BUG_TRACKER != "GitLabDashboard"
    refs:
      - master
  image:   
    name: checkmarx/${CHECKMARX_DOCKER_IMAGE}
    entrypoint: ['']
  script:
    - env
    - cat ${CHECKMARX_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar
      --scan 
      --app="${CI_PROJECT_NAME-$CI_COMMIT_REF_NAME}" 
      --namespace="${CHECKMARX_NAMESPACE}" 
      --repo-name="${CHECKMARX_REPO_NAME}" 
      --repo-url="${CHECKMARX_REPO_URL}" 
      --cx-team="${CHECKMARX_TEAM}"
      --cx-project="${CHECKMARX_PROJECT}" 
      --branch="${CI_COMMIT_REF_NAME}"
      --bug-tracker="${CHECKMARX_BUG_TRACKER}"
      --checkmarx.scan-preset="${CHECKMARX_SCAN_PRESET}"
      --cx-flow.filter-severity="${CHECKMARX_FILTER_SEVERITY}"
      --cx-flow.filter-cwe="${CHECKMARX_FILTER_CWE}"
      --cx-flow.filter-category="${CHECKMARX_FILTER_CATEGORY}"
      --cx-flow.filter-status="${CHECKMARX_FILTER_STATUS}"
      --checkmarx.exclude-files="${CHECKMARX_EXCLUDE_FILES}"
      --checkmarx.exclude-folders="${CHECKMARX_EXCLUDE_FOLDERS}"
      --checkmarx.incremental=${CHECKMARX_INCREMENTAL}
      --project-id="${CI_PROJECT_ID}" 
      --spring.profiles.active="${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}" 
      --f=. 
      ${CXFLOW_PARAMS}

checkmarx-scan-dashboard:
  stage: test
  only:
    variables:
      - $CHECKMARX_BUG_TRACKER == "GitLabDashboard"
    refs:
      - master
  image:   
    name: checkmarx/${CHECKMARX_DOCKER_IMAGE}
    entrypoint: ['']
  script:
    - cat ${CHECKMARX_CONFIG} > application.yml
    - java -jar /app/cx-flow.jar --spring.config.location=./application.yml
      --scan 
      --app="${CI_PROJECT_NAME-$CI_COMMIT_REF_NAME}" 
      --namespace="${CHECKMARX_NAMESPACE}" 
      --repo-name="${CHECKMARX_REPO_NAME}" 
      --repo-url="${CHECKMARX_REPO_URL}" 
      --cx-team="${CHECKMARX_TEAM}" 
      --cx-project="${CHECKMARX_PROJECT}" 
      --branch="${CI_COMMIT_REF_NAME}"
      --bug-tracker="${CHECKMARX_BUG_TRACKER}"
      --checkmarx.scan-preset="${CHECKMARX_SCAN_PRESET}"
      --cx-flow.filter-severity="${CHECKMARX_FILTER_SEVERITY}"
      --cx-flow.filter-cwe="${CHECKMARX_FILTER_CWE}"
      --cx-flow.filter-category="${CHECKMARX_FILTER_CATEGORY}"
      --cx-flow.filter-status="${CHECKMARX_FILTER_STATUS}"
      --checkmarx.exclude-files="${CHECKMARX_EXCLUDE_FILES}"
      --checkmarx.exclude-folders="${CHECKMARX_EXCLUDE_FOLDERS}"
      --project-id="${CI_PROJECT_ID}" 
      --spring.profiles.active="${CHECKMARX_ENABLED_VULNERABILITY_SCANNERS}" 
      --f=. 
      ${CXFLOW_PARAMS}
  artifacts:
    reports:
      sast: gl-sast-report.json
      dependency_scanning: gl-dependency-scanning-report.json
